[username]
show_always = true
format = "[${user}](fg:#83a598)"

[hostname]
ssh_only = false
format = "[@](fg:#688080)[${hostname}](fg:#688080) "

[line_break]
disabled = true

[c]
symbol = " "
style = "fg:#A8B9CC"

[conda]
symbol = " "
style = "fg:#83a598"

[directory]
read_only = " 󰌾"
style = "fg:#689d6a"
truncation_length = 4


[docker_context]
symbol = " "
style = "fg:#0db7ed"

[python]
symbol = " "
style = "fg:#3776AB"

[golang]
symbol = " "
style = "fg:#00ADD8"

[lua]
symbol = " "
style = "fg:#83a598"

[memory_usage]
symbol = "󰍛 "
style = "fg:#d3869b"

[nodejs]
symbol = " "
style = "fg:#8CC84B"

[rust]
symbol = " "
style = "fg:#B7410E"

[git_branch]
symbol = " "
style = "fg:#79740e"

[git_status]
#symbol = " "
style = "fg:#98971a"

[env_var]
variable = "PYTHON_ENV"
symbol = "🐍="
style = "fg:#928374"

[cmd_duration]
min_time = 2000
style = "fg:#bdae93"

[character]
success_symbol = "[❯](fg:#83a598)"
error_symbol = "[❯](fg:#fb4934)"
